### ISSUE TITLE
build-win32 failed (Python.h not found)

### ISSUE THREAD

**Issue by zjxian** [ambrop72/badvpn#40]
I'm trying to build the latest badvpn for win32 on a Cenos 6 linux workstation and comes up with following error.

make[4]: Entering directory '/tmp/nix-build-libxml2-2.9.4.drv-0/libxml2-2.9.4/python'
  CC       libxml.lo
  CC       libxml2-py.lo
  CC       types.lo
In file included from types.c:9:0:
libxml_wrap.h:1:20: fatal error: Python.h: No such file or directory
compilation terminated.
libxml2-py.c:3:20: fatal error: Python.h: No such file or directory
compilation terminated.
libxml.c:14:20: fatal error: Python.h: No such file or directory
compilation terminated.
make[4]: *** [Makefile:627: types.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [Makefile:627: libxml2-py.lo] Error 1
make[4]: *** [Makefile:627: libxml.lo] Error 1
make[4]: Leaving directory '/tmp/nix-build-libxml2-2.9.4.drv-0/libxml2-2.9.4/python'
make[3]: *** [Makefile:684: all-recursive] Error 1
make[3]: Leaving directory '/tmp/nix-build-libxml2-2.9.4.drv-0/libxml2-2.9.4/python'
make[2]: *** [Makefile:524: all] Error 2
make[2]: Leaving directory '/tmp/nix-build-libxml2-2.9.4.drv-0/libxml2-2.9.4/python'
make[1]: *** [Makefile:1440: all-recursive] Error 1
make[1]: Leaving directory '/tmp/nix-build-libxml2-2.9.4.drv-0/libxml2-2.9.4'
make: *** [Makefile:859: all] Error 2
builder for ‘/nix/store/p9hh6fb4s0d24ymsgl7lr5247c2p7nj2-libxml2-2.9.4.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/y09zrmyn2f3d3any18kwfx2sqign9kk5-libarchive-3.2.1.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/c6vg54vrmx5ax4scxhmdz3pgv96angl3-mingw-w64-4.0.6-headers’
cannot build derivation ‘/nix/store/j853wfk64jxyxd59876ljyyjd3xzx6k7-cmake-3.6.0.drv’: 1 dependencies couldn't be built
killing process 25305
cannot build derivation ‘/nix/store/g23hs781fjygkfrnsiby9mmf9g10b6q7-badvpn-i686-w64-mingw32.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/g23hs781fjygkfrnsiby9mmf9g10b6q7-badvpn-i686-w64-mingw32.drv’ failed

Full build log is here
[build.zip](https://github.com/ambrop72/badvpn/files/672570/build.zip)

I'm not familiar with NixOS, but I tried to build (configure && make) the package "libxml2-2.9.4" under /nix/store and that succeeded.

**Comment by ambrop72** [comment]
Hi,
The error is in a native (not cross compiled) package so this is probably an upstream issue with Nixpkgs, likely the package fails when Nix is not running with the sandboxing configured.
I have rebased my nixpkgs cross-mingw-nss branch on top of the latest and pushed it as "cross-mingw-nss2". This should help because it should now be able to pick up the build of that package from the public cache. So please try with my cross-mingw-nss2 branch.

**Comment by ambrop72** [comment]
Actually that will probably not solve it. The issue seems to be a bug in nixpkgs that will cause the cross-compilation settings to try to rebuild some native packages, along with the build failure in libxml2.

The only solution I can think of is to
- Setup multi-user mode for Nix: http://nixos.org/nix/manual/#ssec-multi-user
- And then enable sandboxing: "build-use-sandbox = true" in /nix/etc/nix/nix.conf.
-- OR --
Use a NixOS virtual machine, which has this already setup.

**Comment by ambrop72** [comment]
Anyway, depending on which components you need (particularly if you only need tun2socks, so there's no library dependencies), it might be easier to build with Visual Studio and CMake.

**Comment by zjxian** [comment]
Branch "cross-mingw-nss2" failed with same error. I'm not familiar with building linux project with VS and CMake. I'll try NixOS VM and report any problem later.

**Comment by ambrop72** [comment]
Windows build instructions are currently out of date unfortunately, the best approach is manual with VS+Cmake...
