### ISSUE TITLE
ld.gold linking error

### ISSUE THREAD

**Issue by wongsyrone** [ambrop72/badvpn#52]
latest git HEAD

ld.gold: error: objs/tun2socks/badvpn/lwip/custom/sys.o: multiple definition of 'tcp_timer_needed'
ld.gold: objs/tun2socks/badvpn/lwip/src/core/timeouts.o: previous definition here
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

my temp fix:

```diff
diff --git a/lwip/custom/lwipopts.h b/lwip/custom/lwipopts.h
index f2db0ef3..573a2e29 100644
--- a/lwip/custom/lwipopts.h
+++ b/lwip/custom/lwipopts.h
@@ -72,6 +72,8 @@
 #define LWIP_DONT_PROVIDE_BYTEORDER_FUNCTIONS
 #define LWIP_SINGLE_NETIF 1
 
+#define LWIP_TUN2SOCKS_CHANGE
+
 /*
 #define LWIP_DEBUG 1
 #define IP_DEBUG LWIP_DBG_ON
diff --git a/lwip/custom/sys.c b/lwip/custom/sys.c
index dbc1f209..04f16f22 100644
--- a/lwip/custom/sys.c
+++ b/lwip/custom/sys.c
@@ -36,6 +36,8 @@ u32_t sys_now (void)
     return btime_gettime();
 }
 
+/*
 void tcp_timer_needed(void)
 {
 }
+*/
diff --git a/lwip/src/core/timeouts.c b/lwip/src/core/timeouts.c
index 1290661d..88468e2b 100644
--- a/lwip/src/core/timeouts.c
+++ b/lwip/src/core/timeouts.c
@@ -147,12 +147,14 @@ tcpip_tcp_timer(void *arg)
 void
 tcp_timer_needed(void)
 {
+#ifndef LWIP_TUN2SOCKS_CHANGE
   /* timer is off but needed again? */
   if (!tcpip_tcp_timer_active && (tcp_active_pcbs || tcp_tw_pcbs)) {
     /* enable and start timer */
     tcpip_tcp_timer_active = 1;
     sys_timeout(TCP_TMR_INTERVAL, tcpip_tcp_timer, NULL);
   }
+#endif
 }
 #endif /* LWIP_TCP */
 

```

**Comment by ambrop72** [comment]
Hey,

I added `#define LWIP_TIMERS 0` to `lwipopts.h`, omitted `timeouts.c` from compilation, and defined a dummy `tcp_timer_needed` in `lwip/custom/sys.c`. If you do the same it should build.

The reason is that since tun2socks never calls `sys_check_timeouts`, the timeouts code was was just a waste of resources. tun2socks already repeatedly calls `tcp_tmr`. This seems to be enough for things to work, but there are other timers that we *should* be calling periodically (`ip_reass_tmr`, `nd6_tmr`, `ip6_reass_tmr`). This seems like an issue tun2socks has had ever seen though I haven't actually seen any ill effects. I will try to fix it soon - luckily these 3 timers need a period of 1 second, exactly 4 times the period for `tcp_tmr`, so a simple counter in `tcp_timer_handler` can be used to implement them.

**Comment by wongsyrone** [comment]
> If you do the same it should build.

Unfortunately not. Just merged your lwip changes.

failed log: https://travis-ci.org/fuckshadows/fuckshadows-android/builds/279797388
success log with changed above: https://travis-ci.org/fuckshadows/fuckshadows-android/builds/279804887

**Comment by ambrop72** [comment]
Ah, the issue is you are actually building `timeouts.c` which defines `tcp_timer_needed` even with `LWIP_TIMERS=0`, while I was not and therefore had to add a separate definition. I pushed a change that fixes it, so just merge that and keep building `timeouts.c`.

**Comment by wongsyrone** [comment]
I will try when back home. Thanks for quick response.

**Comment by wongsyrone** [comment]
off-topic:

Just noticed compile-tun2sock.sh is not being synced.

**Comment by wongsyrone** [comment]
Confirmed.
