### ISSUE TITLE
How can I add standard socks Udp Associate feature into this tun2socks?

### ISSUE THREAD

**Issue by GreatFireWall** [ambrop72/badvpn#56]
This project is complex, would you give me a starting point ?

**Comment by ambrop72** [comment]
Hi,
- Software is based on a single-threaded event-driven architecture, so read up on event loops etc.. The event loop implementation is in system/BReactor_badvpn.{h,c}.
- To work with UDP, use the existing BDatagram facility (look at system/BDatagram.h for the API).
- The tun2socks main implementation is in tun2socks/tun2socks.c. The most important functions here are:
  - process_device_udp_packet (called to handle a UDP packet coming in from the TUN and needs to be sent),
  - BTap_Send - use this when you receive a packet to send it into the TUN, see for example what udpgw_client_handler_received does.
- The current UDP support in tun2socks uses the custom "udpgw" server - you will need to add conditionals (e.g. in the above mentioned places) so that UDP support is provided either by udpgw or UDP Associate.
- You will need to maintain a collection of UDP "associations", and you will need to associate packets coming from TUN with a association possibly involving creation of one. Each "association" object will be responsible for a particular (LocalPort, RemotePort, LocalAddress, RemoteAddress) combination.
- Each association object will need to do the SOCKS handshaking using TCP. You can probably copy a lot of code from current socksclient/ code which is for TCP connections. It would be best to separate this code into its own module. Or maybe the existing socksclient could be extended to also do UDP Associate, your call.
- You will probably need to buffer packets within associations while you are doing the SOCKS handshaking, to prevent undesired loss.

I need to go right now, I can provide further guidance...

**Comment by GreatFireWall** [comment]
Well, thanks your detailed guides. 
I go to have a try first.

**Comment by GreatFireWall** [comment]
Hi,
Another question: Why not use map(dictionary) (use source port or destination port as key) to manage connections instead of AVL tree for enhance performance of finding connection in "UdpGwClient_SubmitPacket.c Line 529"?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
@GreatFireWall give #71 a try

**Comment by diegocr** [comment]
While waiting for #71 to get merged (any eta?) a good workaround would be using [dns2socks](https://sourceforge.net/projects/dns2socks/)

**Comment by GreatFireWall** [comment]
Emm.. I had built myself product to implement this feature.. 
If anyone is interested, you can take a look [Win2Socks](https://win2socks.com).

**Comment by diegocr** [comment]
Interesting :)

**Comment by ambrop72** [comment]
@GreatFireWall, it is not clear to me if your product is based on tun2socks code?

**Comment by GreatFireWall** [comment]
> @GreatFireWall, it is not clear to me if your product is based on tun2socks code?

No, I completely developed it myself. I am sorry to make you feel confused. :)

**Comment by ambrop72** [comment]
@GreatFireWall, okay good for you, thanks for the info!

**Comment by GreatFireWall** [comment]
@ambrop72 You're welcome.
