### ISSUE TITLE
configuring proxies to several openvpn connections

### ISSUE THREAD

**Issue by Enrikeyo** [ambrop72/badvpn#62]
Is it possible to do the following with tun2socks?
I have open five openvpn connections in windows 10 using tun/tap and I need to develop a java application that makes httpconnection where I can indicate which of the openvpn connections I want to connect to.

The idea would be using tun2socks to configure 5 proxies, each of one associated to each of the openvpn connections, and through httpconnection can connect to each of the proxies.
Is this possible?

thank you

**Comment by ambrop72** [comment]
Not sure if I understand your requirements. If you needs to access a specific machine through a specific VPN and the VPNs are for separate networks, just connect to the right address. But if the VPNs are different paths to the same network, then you will need some hack. Maybe you can afford to only run one VPN at a time, the one which you need to use?

Otherwise things indeed get ugly. You could possibly use tun2socks but you would need to modify it so that:
- It "fakes" remote addresses, e.g. if application connects to 10.0.1.X, it connects through VPN number X. Forwarding just based on the IP address might not be enough and you may need to pass information though other channels depending on how flexible you need this to be.
- Tun2socks currently uses SOCKS5 for the remote end, while for your case it might be easier if it just opened a plain TCP connection.

Maybe you were thinking of having this application of yours accepts SOCKS connections from tun2socks, but doesn't seem to solve anything directly because you wouldn't have any useful information to work with - notably you wouldn't have the original destination address/port, which tun2socks does have.

**Comment by Enrikeyo** [comment]
Hello:

I have tried it configuring two tap windows connections:

tap1: this connection is used to connect to the openvpn server
tap2: this connection I wanted to use to define a proxy with tun2socks so that it redirects to openvpn, that is to say it redirects to the tap1 connection.

The tap1 connection to the openvpn server has the following logs information:

OpenVPN 2.3.11 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [PKCS11] [IPv6] built on May 10 2016
Windows version 6.2 (Windows 8 or greater) 64bit
library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.09
WARNING: --ping should normally be used with --ping-restart or --ping-exit
Socket Buffers: R=[65536->65536] S=[65536->65536]
Attempting to establish TCP connection with [AF_INET]5.62.36.40:443 [nonblock]
TCP connection established with [AF_INET]5.62.36.40:443
TCPv4_CLIENT link local: [undef]
TCPv4_CLIENT link remote: [AF_INET]5.62.36.40:443
TLS: Initial packet from [AF_INET]5.62.36.40:443, sid=a43ec8dd f2473504
WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
VERIFY OK: nsCertType=SERVER
Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
[server] Peer Connection Initiated with [AF_INET]5.62.36.40:443
SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 100.124.40.1,redirect-gateway def1,ping 9,ping-restart 30,explicit-exit-notify 1,sndbuf 196608,rcvbuf 196608,route-gateway 100.124.40.1,topology subnet,redirect-gateway def1,ifconfig-ipv6 2001:db8:123::2/64 2001:db8:123::1,route-ipv6 2000::/3 2001:db8:123::1,explicit-exit-notify 2,comp-lzo no,ifconfig 100.124.40.123 255.255.254.0,peer-id 0'
OPTIONS IMPORT: timers and/or timeouts modified
OPTIONS IMPORT: LZO parms modified
OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Socket Buffers: R=[65536->196608] S=[65536->196608]
OPTIONS IMPORT: --ifconfig/up options modified
OPTIONS IMPORT: route-related options modified
OPTIONS IMPORT: peer-id set
OPTIONS IMPORT: adjusting link_mtu to 1563
ROUTE_GATEWAY 192.168.0.1/255.255.255.0 I=11 HWADDR=e4:70:b8:0d:7e:7e
do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=1
open_tun, tt->ipv6=0
TAP-WIN32 device [tap1] opened: \\.\Global\{64B88339-ACAB-403C-87A5-1DB2744E6225}.tap
TAP-Windows Driver Version 9.9 
Set TAP-Windows TUN subnet mode network/local/netmask = 100.124.40.0/100.124.40.123/255.255.254.0 [SUCCEEDED]
Successful ARP Flush on interface [10] {64B88339-ACAB-403C-87A5-1DB2744E6225}
Successfully deleted previously set dynamic IP/netmask: 100.124.65.15/255.255.192.0
Succeeded in adding a temporary IP/netmask of 100.124.40.123/255.255.254.0 to interface {64B88339-ACAB-403C-87A5-1DB2744E6225} using the Win32 IP Helper API
TEST ROUTES: 5/5 succeeded len=5 ret=1 a=0 u/d=up
Initialization Sequence Completed

The connection tap2 tried to configure it:
badvpn-tun2socks.exe --tundev "tap0901:tap2:100.124.40.123:100.124.40.0:255.255.254.0" --netif-ipaddr 100.124.40.123 --netif-netmask 255.255.254.0 --socks-server-addr 127.0.0.1:1080

Finally I set the firefox browser to use proxy 127.0.0.1:1080 but I can not redirect it correctly.

Is it possible to do something similar with tap2socks?

Thank you very much

**Comment by ambrop72** [comment]
I don't think you understand what tun2socks does. Tun2socks accepts raw TCP connections and forwards them via a SOCKS server. Tun2socks is a client to a SOCKS server, it does not provide a SOCKS server.

I honestly have no idea what you are trying to achieve and why you think tun2socks would help.
