### ISSUE TITLE
EINTR (Interrupted system call

### ISSUE THREAD

**Issue by kwapster** [ambrop72/badvpn#66]
I am having trouble running badvpn. It starts but abruptly ends after 2 minutes or so. No logs (tried debug), no syslog either. I have posted a strace. Any help is appreciated.

[badvpn.txt](https://github.com/ambrop72/badvpn/files/2259662/badvpn.txt)

**Comment by ambrop72** [comment]
Hi,
The EINTR seem to be because the console is being resized (SIGWINCH signals), they should be harmless. The real error is when the program is suddenly killed by SIGKILL signal. It is not clear from the strace why this is. Is some other program killing it? Do you see something in the kernel log (dmesg)? Sometimes the kernel itself kills a process for various reasons such as memory exhaustion.

**Comment by kwapster** [comment]
I'm on an Openvz install which shares the kernel with it's node so logs are out of it.
This is really quite weird. Still quits after a fresh system install.

**Comment by ambrop72** [comment]
I'm guessing it's due to some kind of restriction being implemented. Sorry I can't help further with this.
