### ISSUE TITLE
tcp_free_acked_segments: lwip assertion failure: tcp_receive: valid queue length

### ISSUE THREAD

**Issue by Mygod** [ambrop72/badvpn#85]
I suspect there is a race condition in this code. See some discussions here: https://github.com/shadowsocks/shadowsocks-android/issues/2285#issuecomment-522587603

**Comment by ambrop72** [comment]
I will look into it. However, note that all the tun2socks code in this repository is single-threaded.

**Comment by ambrop72** [comment]
The `unacked` and `unsent` are queues of `tcp_seg` (the former contains segments that were sent and are awaiting acknwledgement, the latter contains segments that have not yet been sent or have been queued for re-sending). Each `tcp_seg` has a pbuf chain attached representing the packet data. The `snd_queuelen` is supposed to be equal to the total number of pbufs (not pbuf chains) in these two queues together, so a segment contributes exactly the number of pbufs on its chain (`pbuf_clen(seg->p)`). That's why `snd_queuelen` is incremented by `pbuf_clen` for each new segment added in `tcp_write`, and decremented by `pbuf_clen` for each segment removed in `tcp_free_acked_segments` (the code you linked).

However, while looking at the code, I have found that there is a bug in `tcp_split_unsent_seg` whereby simply increments `snd_queuelen` by one after splitting the first `unsent` segment into two segments; it does not consider the actual chain lengths of the modified first segment and the newly inserted segment.

This appears to be fixed in the lwip master code: http://git.savannah.nongnu.org/cgit/lwip.git/tree/src/core/tcp_out.c#n928, and the bug report is https://savannah.nongnu.org/bugs/?52692. If you don't want to update lwip now, try cherry-picking the fix: http://git.savannah.nongnu.org/cgit/lwip.git/commit/src/core/tcp_out.c?id=04b983b4f376697f04980b8d547fa4d03aa10600

**Comment by Mygod** [comment]
Closed via #86.
